# Generated by Django 5.0.2 on 2024-02-24 17:08

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homes", "0001_initial"),
        ("providers", "0002_add_category_icon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="record date"
                    ),
                ),
                (
                    "prev_numbers",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The numbers on the counter at the end of the previous period",
                        verbose_name="previous numbers",
                    ),
                ),
                (
                    "current_numbers",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        help_text="The current numbers on the counter",
                        verbose_name="current numbers",
                    ),
                ),
                (
                    "total_to_pay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="total to pay",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="total paid",
                    ),
                ),
                (
                    "is_paid",
                    models.BooleanField(blank=True, default=False, verbose_name="paid"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "home",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="homes.home",
                        verbose_name="home",
                    ),
                ),
                (
                    "payment_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="records",
                        to="providers.paymentplan",
                        verbose_name="payment plan",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="providers.provider",
                        verbose_name="provider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "record",
                "verbose_name_plural": "records",
            },
        ),
    ]
