# Generated by Django 5.0.2 on 2024-02-29 08:56

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="record_date",
            field=models.DateField(
                db_index=True,
                default=datetime.date.today,
                help_text="Any date in the period for which you are going to pay",
                verbose_name="record date",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="total_to_pay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=Decimal("0"),
                help_text="Leave blank to auto-calculate",
                max_digits=12,
                verbose_name="total to pay",
            ),
        ),
    ]
