# Generated by Django 5.0.2 on 2024-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("providers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-solid fa-gear", "&#xf013; - Default icon"),
                    ("fa-solid fa-lightbulb", "&#xf0eb; - Energy"),
                    ("fa-solid fa-droplet", "&#xf043; - Water"),
                    ("fa-solid fa-fire-flame-simple", "&#xf46a; - Natural gas"),
                    ("fa-solid fa-temperature-arrow-up", "&#xe040; - Heating"),
                    ("fa-solid fa-screwdriver-wrench", "&#xf7d9; - Maintenance"),
                ],
                default="fa-solid fa-gear",
                max_length=50,
                verbose_name="category icon",
            ),
        ),
    ]
