# Generated by Django 5.0.2 on 2024-02-21 19:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="The location of the home/apartment. Usually, geographical location, post address or similar.",
                        max_length=300,
                        null=True,
                        verbose_name="location",
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="The area of the home or apartment in the square meters, fts, etc.",
                        max_digits=12,
                        verbose_name="area",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "home",
                "verbose_name_plural": "homes",
                "ordering": ("title",),
            },
        ),
    ]
